name: CICD

on:
  push:

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  semantic:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: semantic

  release:
    runs-on: ${{ matrix.os }}
    needs: [semantic]
    if: semantic.outputs.new_release_published == 'true'
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: |
          npm install
          npm run package
          npm run make
          if [[ "$github.ref == 'refs/heads/next'" ]] then
            npm run publish --prerelease
          else
            npm run publish
          fi
        shell: bash
